services:

  jenkins:
    build: ./jenkinsCasC
    restart: always
    volumes:
      - ./JenkinsHome:/var/jenkins_home:rw
    ports:
      - "8080:8080"
    environment:
      - CASC_JENKINS_CONFIG=/user/local/jenkins-config.yaml
      - TZ=Europe/Moscow
    depends_on:
      - docker-ssh-agent
      - gitlab

  jnlp-agent:
    build: ./jnlp-agent
    restart: always
    depends_on:
    - jenkins

  docker-ssh-agent:
    build: ./ssh-agent
    restart: always
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClDjCi8cbTwwPF109h5WpjrPT8DyuB1D2PG/DpDazRYiBnX0G57vBkJUiQj3hR6VrOJHPuQjUcULyXFr6ONkUzzMs14FBelFLJCzXEUV6oLutvbabvSpTfZIHQjw3n/7BdDpRRMRnFonbmZSTGEvm9XprHf4MNDzdo7iuCFu6462BEqVqAfE/nEu+k++oKZz4PTQGSPsIwWoLDzCQ7ilzs+UWj37kX+GQCk0msoDyOqhlhQuBnyAWnOW9Vd8zW0WUKiBZO0al9VfXNNx9iVWsdAgnlVovqvz22RhuPZSA92IeyMTGrShdzrSLnw+m3Xgz1kha5w3nlPP6NO4MvL/I7

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab:80'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "8081:80"  # Внешний порт GitLab
      - "2222:22"  # SSH доступ
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    shm_size: '256m'